[package]
name = "nuwa-inference"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
log.workspace = true
tracing.workspace = true

[target.'cfg(not(target_os = "android"))'.dependencies]
llama-rs = "0.2"

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"
